name: Update charts

on:
  schedule:
    - cron: '0 0 * * 3'  # Runs every Wednesday at 00:00 UTC
  workflow_dispatch:     # Allows manual trigger

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          cd src
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run scraper
        run: |
          cd src
          python scraper.py

      - name: Commit changes
      
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update charts
